class Strings{
  /// For change language
  static const spanish = 'ESPAÑOL';
  static const english = 'ENGLISH';
  static const french = 'FRANÇAIS';
  static const italian = 'ITALIANO';
  static const portuguese = 'PORTUGUÊS';
  static const german = 'DEUTSCH';
  static const selectedLanguageCode = 'selectedLanguageCode';
  static const selectedLanguage = 'selectedLanguage';

  static const List mciNames = ['MONICA', 'SOFIA', 'LAURA'];
  static const List mciIDs = ['CFFAA4', 'CFFBD6', 'DFF87F'];
  static const nothing = '';
  static const String mciId = 'MAC. F4:12:FA:EC:C5:65';
  static const String man = 'Hombre';
  static const String women = 'Mujer';
  static const String active = 'Activo';
  static const String inactive = 'Inactivo';
  static const String all = 'todos';
  static const individual = 'Individual';
  static const automatics = 'Automaticos';
  static const String typeBT = 'BT';
  static const String typeBLE = 'BLE';
  static const String administrator = 'Administrador';
  static const String beautician = 'Esteticista';
  static const String yes = 'Si';
  static const String no = 'No';
  static const String bioJacket = 'Bio-Jacket';
  static const String pant = 'Pantalón';
  static const String upperBack = 'Espalda alta';
  static const String middleBack = 'Espalda media';
  static const String lowerBack = 'Lumbares';
  static const String glutes = 'Glúteos';
  static const String hamstrings = 'Isquios';
  static const String chest = 'Pecho';
  static const String abdominals = 'Abdominales'; /// Add
  static const String abdomen = 'Abdomen';
  static const String legs = 'Piernas';
  static const String arms = 'Brazos';
  static const String calves = 'Pantorrillas';
  static const String extra = 'Extra';

  // static const String fatFreeHydration = 'Hidratación sin grasa';
  // static const String waterBalance = 'Equilibrio hidrico';
  // static const String imc = 'Imc';
  // static const String bodyFat = 'Masa grasa';
  // static const String muscle = 'Músculo';
  // static const String skeleton = 'Esqueleto';
  // static const String toTreat = 'A tratar';
  // static const String toMonitor = 'A vigilar';
  // static const String nearNormal = 'Cerca de la norma';
  // static const String normal = 'NORMAL';
  // static const String veryGood = 'Muy bien';
  // static const String excellent = 'Excelente';
  // static const selectProgramType = 'seleccionar tipo de programa';
  // static const select = 'Selectionar';
  // static const selectProgram = 'Seleccionar programa';
  // static const onlyForClients = 'Solo para clientes con';
  // static const contactWithUsForDevice = 'Contacte con nosotros para obtener nuestro dispositivo de análisis de la composición corporal.';
  // static const String selectClient = 'Seleccionar Cliente';
  // static const String name = 'Nombre';
  // static const String nick = 'Nick';
  // static const String gender = 'Género';
  // static const String height = 'Altura (cm)';
  // static const String weight = 'Peso (kg)';
  // static const String email = 'E-mail'; /// Duplicate
  // static const String takeNewMeasurement = 'Tomar Nueva Medida';
  // static const String howToTakeMeasurement = 'Cómo Obtener Una Medida';
  // static const String clients = 'Clientes';
  // static const String clientList = 'Lista de clientes';
  // static const String administratorList = 'Lista de Administradores';
  // static const String createNewClient = 'Crear nuevo cliente';
  // static const String createProfile = 'Crear ficha';
  // static const String tutorials = 'Tutoriales';
  // static const String firstSteps = 'Primeros pasos';
  // static const String software = 'Software';
  // static const String commonIncidents = 'Incidencias comunes';
  // static const String license = 'Licencia';
  // static const String howToPrepareEquipment = 'Como preparar el equipo para el tratamiento';
  // static const String program = 'Programa';
  // static const String individuals = 'Individuales';
  // static const String createProgram = 'Crear programa';
  // static const String centerManagement = 'Gestión de centros';
  // static const String administrators = 'Administradores';
  // static const String beauticiansList = 'Lista de esteticístas';
  // static const String createNew = 'Crear nuevo';
  // static const String licenseData = 'Datos licencia';
  // static const String licenseNumber = 'N° licencia';
  // static const String address = 'Dirección';
  // static const String city = 'Ciudad';
  // static const String province = 'Provincia';
  // static const String country = 'País';
  // static const String phone = 'Teléfono';
  // static const String number = 'Numero';
  // static const String validateLicense = 'Validar licencia';
  // static const String licenseNo = 'N° de licencia';
  // static const String mci = 'MCI';
  // static const String type = 'Tipo';
  // static const String status = 'Estado';
  // static const String recharge = 'RECARGAR';
  // static const String info = 'INFORMACIÓN';
  // static const String clientFile = 'Ficha Cliente';
  // static const String administratorFile = 'Ficha administrador';
  // static const String beauticianFile = 'Ficha esteticístas';
  // static const String personalData = 'Datos Personales';
  // static const String birthDate = 'Fecha Nacimiento';
  // static const String activities = 'Actividad';
  // static const String cards = 'Bonos'; /// Duplicate
  // static const String bioimpedancia = 'Bioimpedancia'; /// Duplicate
  // static const String activeGroups = 'Grupos Activos';
  // static const String pleaseSelect = 'por favor seleccione';
  // static const String date = 'FECHA';
  // static const String hour = 'HORA';
  // static const String points = 'PUNTOS';
  // static const String eKcal = 'E-KCAL';
  // static const String addPoints = 'Añadir bonos';
  // static const String consumedPoints = 'Bonos consumidos';
  // static const String availablePoints = 'Bonos disponible';
  // static const String quantity = 'Cantidad';
  // static const String total = 'Total';
  // static const String evolution = 'Evolución';
  // static const String calculatedValue = 'Valor calculado';
  // static const String reference = 'Referencia';
  // static const String result = 'Resultado';


  // static const String profile = 'Perfil';
  // static const String registrationDate = 'Fecha alta';
  // static const String sessionControl = 'Control de sesiones';
  // static const String timeControl = 'Control de tiempo';
  // static const String resetPassword = 'Restablecer contraseña';
  // static const String start = 'Inicio';
  // static const String end = 'Fin';
  // static const String bonuses = 'Bonos';
  // static const String client = 'Cliente';
  // static const String programName = 'Nombre programa';
  // static const String frequency = 'Frecuencia';
  // static const String pulse = 'Pulso';
  // static const String ramp = 'Rampa';
  // static const String contraction = 'Contracción';
  // static const String pause = 'Pausa';
  // static const String programNumber = 'Número del programa';
  // static const String programName2 = 'Nombre del programa';
  // static const String equipment = 'Equipamiento';
  // static const String configurationTab = 'Configuración';
  // static const String cronaxiaTab = 'Cronaxia';
  // static const String createSequence = 'Crear secuencia';
  // static const String programSelection = 'Selección programa';
  // static const String order = 'Orden';
  // static const String duration = 'Duración';
  // static const String adjustment = 'Ajuste';
  // static const String action = 'Acción';
  // static const String automaticProgrammes = 'Programas automáticos';
  // static const String celluliteProgramDescription = 'Basado en el programa individual de celulitis. Perfecto para tratar la celulitis y la flacidez corporal.';
  // static const String newPassword = 'Nueva contraseña';
  // static const String repeatPassword = 'Repetir contraseña';
  // static const String logIn = 'Iniciar sesión';
  // static const String closeApplication = '¿Cerrar aplicación?';
  // static const String cancel = 'Cancelar';
  // static const String closeApplicationButton = 'Cerrar aplicación';
  // static const String alertCompleteForm = '¡Alerta!';
  // static const String mustCompleteForm = 'Debes completar el formulario para continuar';
  // static const String emptyPointsError = 'Por favor, ingresa la cantidad de bonos que deseas comprar.';
  // static const String gotIt = '¡Entendido!';
  // static const String confirmDeletion = 'Confirmar eliminación';
  // static const String deleteClientDesc = '¿Estás seguro de que deseas eliminar este cliente?';
  // static const String yesDelete = '¡Sí, estoy seguro!';
  // static const String logout = '¿Cerrar sesión?';
  // static const String logOutButton = 'Cerrar sesión';
  // static const String buyPoints = 'comprar bonos';
  // static const String add = 'Añadir';
  // static const String pointsQuantity = 'Cantidad de bonos';
  // //


  /// Language codes
  static const String englishLanguageCode = 'en';
  static const String spanishLanguageCode = 'es';
  static const String germanLanguageCode = 'de';
  static const String portugueseLanguageCode = 'pt';
  static const String italianLanguageCode = 'it';
  static const String frenchLanguageCode = 'fr';

  ///Images (Icons)
  static const String bgImage = 'assets/icons/bg_image.jpg';
  static const String backIcon = 'assets/icons/back.png';
  static const String logoIModel = 'assets/icons/logo-imodel.png';
  static const String ignitionIcon = 'assets/icons/off.png';
  static const String suitIcon = 'assets/icons/complete-suit-icon.png';
  static const String selectedSuitIcon = 'assets/icons/shorts-icon.png';
  static const String selectedPantIcon = 'assets/icons/shorts-selected.png';
  static const String repeatSession = 'assets/icons/repeat-session.png';
  static const String completeSuitSelected = 'assets/icons/complete-suit-selected.png';
  static const String increaseIcon = 'assets/icons/increase.png';
  static const String decreaseIcon = 'assets/icons/decrease.png';
  static const String armsIcon = 'assets/icons/arms.png';
  static const String abdomenIcon = 'assets/icons/abdomen.png';
  static const String chestIcon = 'assets/icons/chest.png';
  static const String legsIcon = 'assets/icons/legs.png';
  static const String lumbarsIcon = 'assets/icons/lumbars.png';
  static const String upperBackIcon = 'assets/icons/trapezius.png';
  static const String hamstringsIcon = 'assets/icons/hamstrings.png';
  static const String buttocksIcon = 'assets/icons/buttocks.png';
  static const String middleBackIcon = 'assets/icons/dorsal.png';
  static const String arrowHideIcon = 'assets/icons/arrow-hide-tab.png';
  static const String blockMuscleGroupIcon = 'assets/icons/muscle-group-blocked.png';
  static const String buttocksAuto = 'assets/automatic_program/BUTTOCKS_AUTO.png';
  static const String celluliteAuto = 'assets/automatic_program/CELLULITE_AUTO.png';
  static const String hypertrophyAuto = 'assets/automatic_program/HYPERTROPHY_AUTO.png';
  static const String pelvicFloorAuto = 'assets/automatic_program/PELVIC_FLOOR_AUTO.png';
  static const String slimAuto = 'assets/automatic_program/SLIM_AUTO.png';
  static const String toningAuto = 'assets/automatic_program/TONING_AUTO.png';
  static const String arrowDown = 'assets/counter/ARROW-DOWN.png';
  static const String arrowUp = 'assets/counter/ARROW-UP.png';
  static const String pauseIcon = 'assets/icons/pause.png';
  static const String playIcon = 'assets/icons/play.png';
  static const String selectClientIcon = 'assets/icons/select_customer.png';
  static const String ekCalIcon = 'assets/icons/ekcal-icon.png';
  static const String resetIcon = 'assets/icons/RESET-control-panel.png';
  static const String activeIcon = 'assets/icons/green-lighting-ACTIVE.png';
  static const String inActiveIcon = 'assets/icons/grey-lighting-INACTIVE.png';
  static const String iBodyProIcon = 'assets/icons/LOGO IBODYPRO.png';
  static const String newMeasurementIcon = 'assets/icons/new_measurement.png';
  static const String checkIcon = 'assets/icons/check.png';
  static const String removeIcon = 'assets/icons/papelera.png';
  static const String pauseProgramIcon = 'assets/icons/pause_programa.png';
  static const String contractionIcon = 'assets/icons/contraction.png';
  static const String rampIcon = 'assets/icons/ramp.png';
  static const String calvesIcon = 'assets/icons/calves.png';


  /// Body icons - Grupos Activos - Active groups
  static const String abdomenBodyIcon = 'assets/body/abdomen.png';
  static const String avatarBackViewIcon = 'assets/body/Avatar-back-view.png';
  static const String avatarFrontViewIcon = 'assets/body/Avatar-front-view.png';
  static const String brazosIcon = 'assets/body/brazos.png';
  static const String piernasIcon = 'assets/body/cuadriceps.png';
  static const String espaldaMedia = 'assets/body/dorsales.png';
  static const String gluteosIcon = 'assets/body/gluteos.png';
  static const String isquiosIcon = 'assets/body/isquiotibiales.png';
  static const String lumbaresIcon = 'assets/body/lumbares.png';
  static const String pechoIcon = 'assets/body/pecho.png';
  static const String espaldaAlta = 'assets/body/trapecios.png';
  static const String extraIcon = 'assets/body/calves.png';

  ///Automatic program
  // static const String buttocks = 'Buttocks';
  static const String cellulite = 'Cellulite';
  // static const String hypertrophy = 'Hypertrophy';
  // static const String pelvicFloor = 'Pelvic Floor';
  // static const String slim = 'Slim';
  // static const String toning = 'Toning';

  static const String buttocksAutoIcon = 'assets/automatic_program/BUTTOCKS_AUTO.png';
  static const String celluliteAutoIcon = 'assets/automatic_program/CELLULITE_AUTO.png';
  static const String hypertrophyAutoIcon = 'assets/automatic_program/HYPERTROPHY_AUTO.png';
  static const String pelvicFloorAutoIcon = 'assets/automatic_program/PELVIC_FLOOR_AUTO.png';
  static const String slimAutoIcon = 'assets/automatic_program/SLIM_AUTO.png';
  static const String toningAutoIcon = 'assets/automatic_program/TONING_AUTO.png';

  /// Individual programs
  // static const String buttocksIndProgram = 'BUTTOCKS';
  // static const String calibration = 'CALIBRATION';
  // static const String celluliteIndProgram = 'CELLULITE';
  // static const String contractures = 'CONTRACTURES';
  // static const String drainage = 'DRAINAGE';
  // static const String hypertrophyIndProgram = 'HYPERTROPHY';
  // static const String massage = 'MASSAGE';
  // static const String metabolic = 'METABOLIC';
  // static const String pelvicFloorIndProgram = 'PELVIC FLOOR';
  // static const String slimIndProgram = 'SLIM';
  // static const String strength = 'STRENGTH';
  // static const String toningIndProgram = 'TONING';

  static const String buttocksIndividualIcon = 'assets/individual_program/BUTTOCKS.png';
  static const String calibrationIcon = 'assets/individual_program/CALIBRATION.png';
  static const String celluliteIcon = 'assets/individual_program/CELLULITE.png';
  static const String contracturesIcon = 'assets/individual_program/CONTRACTURES.png';
  static const String drainageIcon = 'assets/individual_program/DRAINAGE.png';
  static const String hypertrophyIcon = 'assets/individual_program/HYPERTROPHY.png';
  static const String massageIcon = 'assets/individual_program/MASSAGE.png';
  static const String metabolicIcon = 'assets/individual_program/METABOLIC.png';
  static const String pelvicFloorIcon = 'assets/individual_program/PELVIC_FLOOR.png';
  static const String slimIcon = 'assets/individual_program/SLIM.png';
  static const String strengthIcon = 'assets/individual_program/STRENGTH.png';
  static const String toningIcon = 'assets/individual_program/TONING.png';


  ///Counter / Timer
  static const String min_0_icon = 'assets/counter/0-MIN.png';
  static const String min_1_icon = 'assets/counter/1-MIN.png';
  static const String min_2_icon = 'assets/counter/2-MIN.png';
  static const String min_3_icon = 'assets/counter/3-MIN.png';
  static const String min_4_icon = 'assets/counter/4-MIN.png';
  static const String min_5_icon = 'assets/counter/5-MIN.png';
  static const String min_6_icon = 'assets/counter/6-MIN.png';
  static const String min_7_icon = 'assets/counter/7-MIN.png';
  static const String min_8_icon = 'assets/counter/8-MIN.png';
  static const String min_9_icon = 'assets/counter/9-MIN.png';
  static const String min_10_icon = 'assets/counter/10-MIN.png';
  static const String min_11_icon = 'assets/counter/11-MIN.png';
  static const String min_12_icon = 'assets/counter/12-MIN.png';
  static const String min_13_icon = 'assets/counter/13-MIN.png';
  static const String min_14_icon = 'assets/counter/14-MIN.png';
  static const String min_15_icon = 'assets/counter/15-MIN.png';
  static const String min_16_icon = 'assets/counter/16-MIN.png';
  static const String min_17_icon = 'assets/counter/17-MIN.png';
  static const String min_18_icon = 'assets/counter/18-MIN.png';
  static const String min_19_icon = 'assets/counter/19-MIN.png';
  static const String min_20_icon = 'assets/counter/20-MIN.png';
  static const String min_21_icon = 'assets/counter/21-MIN.png';
  static const String min_22_icon = 'assets/counter/22-MIN.png';
  static const String min_23_icon = 'assets/counter/23-MIN.png';
  static const String min_24_icon = 'assets/counter/24-MIN.png';
  static const String min_25_icon = 'assets/counter/25-MIN.png';
  static const String min_26_icon = 'assets/counter/26-MIN.png';
  static const String min_27_icon = 'assets/counter/27-MIN.png';
  static const String min_28_icon = 'assets/counter/28-MIN.png';
  static const String min_29_icon = 'assets/counter/29-MIN.png';
  static const String min_30_icon = 'assets/counter/30-MIN.png';



  /// Routes
  static const String initialScreen = '/';
  static const String menuScreen = '/MenuScreen';
  static const String settingScreen = '/SettingScreen';
  static const String dashboardScreen = '/DashboardScreen';
  static const String clientScreen = '/ClientScreen';
  static const String tutorialScreen = '/TutorialScreen';
  static const String programsScreen = '/ProgramsScreen';
  static const String licenseScreen = '/LicenseScreen';
  static const String centerManagementScreen = '/CenterManagementScreen';
}